version: "3.9"

services:
  conda-repo-template:
    # Choose one
    # image: utkusarioglu/conda-econ-devcontainer:1.0.14
    # image: utkusarioglu/conda-math-devcontainer:1.0.14
    # image: utkusarioglu/conda-music-devcontainer:1.0.14

    environment:
      PYTHONPATH: /utkusarioglu-com/templates/conda-repo-template
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/templates/conda-repo-template
